### ISSUE TITLE
小问题

### ISSUE THREAD

**Issue by hehe321** [sowish/sqlmapapi_pi#1]
请问关键字能该成特定的url地址吗？比如key='http://www.bjsqlw.com/newshow.php?id=49'？

**Comment by hehe321** [comment]
还有injection.txt和targets.txt里放的有什么联系吗？

**Comment by sowish** [comment]
targets.txt里面存放的是通过百度抓取的url列表，injection.txt存放的是存在sql注入的列表地址。关键字最好是百度语法支持的，例如"inurl:news.php?"，或者是"site:xxx.com"等

**Comment by hehe321** [comment]
话说能检测出具体是什么注入漏洞吗

**Comment by sowish** [comment]
理论上是可以的，这里只做了有和无的判断

**Comment by hehe321** [comment]
set_option.txt里设置的判断注入方式是什么？

**Comment by sowish** [comment]
"tech": "BEUSTQ",
