### ISSUE TITLE
能不能指定查询页码区间？

### ISSUE THREAD

**Issue by chingxuds** [sowish/sqlmapapi_pi#4]
比如说我只想检测30页-50页之间的链接，毕竟前面页面的大多页面都不会存在漏洞，-p指令好像只能传递一个整值

**Comment by sowish** [comment]
可以的，这里指定的页面就是百度抓取url的页面。在search/baidu.py的62行，for page in range(0,int(pages))，for循环里就是抓取的页面数，默认是从第一页（0）开始抓取的，这里稍作修改起始页面就可以了

**Comment by chingxuds** [comment]
多谢了，不过希望下次更新的时候，能够将key和启始页码都做成参数哇
